### ISSUE TITLE
Unable to install python

### ISSUE THREAD

**Issue by pranavbhargava89** [code4policy/modules#34]
For setup, I was able to complete all items except installing python. When I type in the following code on the terminal, it says _"brew: command not found"_

brew install python
brew install node

Just to confirm, I am using bash since the command echo "$SHELL" ends in /bash. Any reason why that be happening? Am I missing something?

**Comment by traghuram** [comment]
Hi Pranav,

I think I may know what's going on, but just to make sure, can you do the following for me:

1 - confirm that you have installed homebrew and run all the requisite steps in the first part of the setup
2 - Go to users and groups, click on your admin profile, and take a screenshot of the line that says "login shell: _____________". I want to see what the path there is
3 - Can you open the bash_profile file and take a screenshot of it for me?

**Comment by traghuram** [comment]
And sorry, one last thing Pranav - can you repost this ticket in the [2022](https://github.com/code4policy/2022) repository? That way everyone else will be able to see it too
