### ISSUE TITLE
Update datetime lesson

### ISSUE THREAD

**Issue by dmil** [code4policy/modules#7]
%m vs %-m

(apparently you can't read `%-m` with strptime)

**Comment by dmil** [comment]
strftime.org says "(platform specific)" of `%-d` and `%-m`flag

**Comment by AlJohri** [comment]
Probably resolved? It works fine for strftime and I don't see it being used for strptime anywhere. And yes "%-m" is platfrom specific but it works on macOS and Ubuntu.
